pipeline {
    agent any

    tools {
        maven 'Maven3'   // this must match the name in Jenkins "Global Tool Configuration"
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Cloning git repo"
                git branch: 'main', url: 'https://github.com/deepa0040/jenkins-cicd-pipeline.git'
                sh 'ls -l'
            }
        }

        stage('Build') {
            steps {
                echo "Running mvn clean package"
                dir('code/sample-java-maven-project') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('code/sample-java-maven-project') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    // Won’t fail if no test results exist
                    junit testResults: 'code/sample-java-maven-project/target/surefire-reports/*.xml',
                          allowEmptyResults: true
                }
            }
        }
    }
}
